env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - '@react-native-community'
  - 'airbnb'
  - 'plugin:flowtype/recommended'
globals:
  Atomics: 'readonly'
  SharedArrayBuffer: 'readonly'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: 'module'
plugins:
  - 'react'
  - 'react-native'
  - 'flowtype'
  - 'import'
  - 'jest'
rules: {
  'prettier/prettier': [
    'off',
    {
      'singleQuote': false,
    }
  ],
  'arrow-body-style': [
    'error',
    'always',
  ],
  'object-shorthand': [
    'error',
    'methods',
  ],
  'max-len': [
    'error',
    {
      'code': 120,
      'ignoreUrls': true,
    },
  ],
  'react/prefer-stateless-function': 0,
  'react/jsx-filename-extension': [
    1,
    {
      'extensions': ['.js', '.jsx']
    }
  ],
  'react/jsx-boolean-value': [
    2,
    'always'
  ],
  'react/destructuring-assignment': 'off',
  'react/self-closing-comp': [
    'error',
    {
      'component': false,
    },
  ],
  'react-native/no-color-literals': 'off',
  'react-native/no-inline-styles': 'off',
  'react-native/no-unused-styles': 'error',
  'react-native/sort-styles': [
    'error',
    'asc',
    {
      'ignoreClassNames': false,
      'ignoreStyleProperties': false,
    },
  ],
  'flowtype/boolean-style': [
    2,
    'boolean'
  ],
  'flowtype/define-flow-type': 1,
  'flowtype/delimiter-dangle': [
    2,
    'always'
  ],
  'flowtype/generic-spacing': [
    2,
    'never'
  ],
  'flowtype/no-mixed': 2,
  'flowtype/no-primitive-constructor-types': 2,
  'flowtype/no-types-missing-file-annotation': 2,
  'flowtype/no-weak-types': 'off',
  'flowtype/object-type-delimiter': [
    2,
    'comma'
  ],
  'flowtype/require-parameter-type': [
    2,
    {
      'excludeArrowFunctions': true
    }
  ],
  'flowtype/require-return-type': [
    2,
    'always',
    {
      'annotateUndefined': 'never',
      'excludeArrowFunctions': true
    }
  ],
  'flowtype/require-valid-file-annotation': 2,
  'flowtype/semi': [
    2,
    'always'
  ],
  'flowtype/space-after-type-colon': [
    2,
    'always'
  ],
  'flowtype/space-before-generic-bracket': [
    2,
    'never'
  ],
  'flowtype/space-before-type-colon': [
    2,
    'never'
  ],
  'flowtype/type-id-match': [
    2,
    '^([A-Z][a-z0-9]+)+Type$'
  ],
  'flowtype/union-intersection-spacing': [
    2,
    'always'
  ],
  'flowtype/use-flow-type': 1,
  'flowtype/valid-syntax': 1,
  'import/no-unresolved': [
    'error',
    {
      'commonjs': false,
      'amd': false
    }
  ],
  'import/named': 'error',
  'import/namespace': 'error',
  'import/default': 'error',
  'import/export': 'error',
  'import/first': 'error',
  'import/order': [
    'error',
    {'groups':
      [
        'builtin',
        'external',
        'parent',
        'sibling',
        'index'
      ]
    }
  ],
}
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
  import/resolver: reactnative
